apiVersion: 1

datasources:
  - name: Lobbying
    uid: lobbying
    type: postgres
    access: proxy
    url: postgres:5432
    database: lobbying
    user: lobby
    secureJsonData:
      password: lobby
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
